# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      days: ${{ steps.days.outputs.days }}

    steps:
      - uses: actions/checkout@v4
      - name: Collect Days
        id: days
        run: |
          directories=$(find . -maxdepth 2 -mindepth 2 -type d -not -path "*/.*")
          echo "days=$(echo "$directories" | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest

    needs:
    - define-matrix

    strategy:
      matrix:
        days: ${{ fromJSON(needs.define-matrix.outputs.days) }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ${{ matrix.days }}
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      working-directory: ${{ matrix.days }}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      working-directory: ${{ matrix.days }}
      run: |
        pytest
